import { UqExt as Uq, assign } from './JkPointshop';
import * as ProductX from './ProductX.ui';
import * as Customer from './Customer.ui';
import * as WebUser from './WebUser.ui';
import * as Contact from './Contact.ui';
import * as Currency from './Currency.ui';
import * as BuyerAccount from './BuyerAccount.ui';
import * as Genre from './Genre.ui';
import * as PointProductLib from './PointProductLib.ui';
import * as Brand from './Brand.ui';
import * as OrderMain from './OrderMain.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as ExchangeDetail from './ExchangeDetail.ui';
import * as ExchangeMain from './ExchangeMain.ui';
import * as DxOrderDetail from './DxOrderDetail.ui';
import * as DxReOrderDetail from './DxReOrderDetail.ui';
import * as DxExchangeDetail from './DxExchangeDetail.ui';
import * as DxExchangeMainState from './DxExchangeMainState.ui';
import * as IxExchangeMainUsedPoint from './IxExchangeMainUsedPoint.ui';
import * as ExchangeDetailDeliver from './ExchangeDetailDeliver.ui';
	
export function setUI(uq: Uq) {
	assign(uq, 'ProductX', ProductX);
	assign(uq, 'Customer', Customer);
	assign(uq, 'WebUser', WebUser);
	assign(uq, 'Contact', Contact);
	assign(uq, 'Currency', Currency);
	assign(uq, 'BuyerAccount', BuyerAccount);
	assign(uq, 'Genre', Genre);
	assign(uq, 'PointProductLib', PointProductLib);
	assign(uq, 'Brand', Brand);
	assign(uq, 'OrderMain', OrderMain);
	assign(uq, 'OrderDetail', OrderDetail);
	assign(uq, 'ExchangeDetail', ExchangeDetail);
	assign(uq, 'ExchangeMain', ExchangeMain);
	assign(uq, 'DxOrderDetail', DxOrderDetail);
	assign(uq, 'DxReOrderDetail', DxReOrderDetail);
	assign(uq, 'DxExchangeDetail', DxExchangeDetail);
	assign(uq, 'DxExchangeMainState', DxExchangeMainState);
	assign(uq, 'IxExchangeMainUsedPoint', IxExchangeMainUsedPoint);
	assign(uq, 'ExchangeDetailDeliver', ExchangeDetailDeliver);
}
export * from './JkPointshop';
