import { UqExt as Uq, assign } from './JkDeliver';
import * as Carrier from './Carrier.ui';
import * as OrderMain from './OrderMain.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as Warehouse from './Warehouse.ui';
import * as DeliverMain from './DeliverMain.ui';
import * as DeliverDetail from './DeliverDetail.ui';
import * as DeliverMainEx from './DeliverMainEx.ui';
import * as CutOffMain from './CutOffMain.ui';
import * as CutOffType from './CutOffType.ui';
import * as DeliverType from './DeliverType.ui';
import * as RequestDetail from './RequestDetail.ui';
import * as Request from './Request.ui';
import * as InsuredInterval from './InsuredInterval.ui';
import * as InsuredType from './InsuredType.ui';
import * as TruckDetail from './TruckDetail.ui';
import * as TruckMain from './TruckMain.ui';
import * as TruckAdditionalTask from './TruckAdditionalTask.ui';
import * as Role from './Role.ui';
	
export function setUI(uq: Uq) {
	assign(uq, 'Carrier', Carrier);
	assign(uq, 'OrderMain', OrderMain);
	assign(uq, 'OrderDetail', OrderDetail);
	assign(uq, 'Warehouse', Warehouse);
	assign(uq, 'DeliverMain', DeliverMain);
	assign(uq, 'DeliverDetail', DeliverDetail);
	assign(uq, 'DeliverMainEx', DeliverMainEx);
	assign(uq, 'CutOffMain', CutOffMain);
	assign(uq, 'CutOffType', CutOffType);
	assign(uq, 'DeliverType', DeliverType);
	assign(uq, 'RequestDetail', RequestDetail);
	assign(uq, 'Request', Request);
	assign(uq, 'InsuredInterval', InsuredInterval);
	assign(uq, 'InsuredType', InsuredType);
	assign(uq, 'TruckDetail', TruckDetail);
	assign(uq, 'TruckMain', TruckMain);
	assign(uq, 'TruckAdditionalTask', TruckAdditionalTask);
	assign(uq, 'Role', Role);
}
export * from './JkDeliver';
