import { UqExt as Uq } from './JkOrder';
import * as Coupon from './Coupon.ui';
import * as Chemical from './Chemical.ui';
import * as SalesRegion from './SalesRegion.ui';
import * as Currency from './Currency.ui';
import * as PackType from './PackType.ui';
import * as Address from './Address.ui';
import * as Country from './Country.ui';
import * as Province from './Province.ui';
import * as City from './City.ui';
import * as County from './County.ui';
import * as InvoiceType from './InvoiceType.ui';
import * as Customer from './Customer.ui';
import * as Organization from './Organization.ui';
import * as Contact from './Contact.ui';
import * as InvoiceInfo from './InvoiceInfo.ui';
import * as Brand from './Brand.ui';
import * as ProductX from './ProductX.ui';
import * as Warehouse from './Warehouse.ui';
import * as WebUser from './WebUser.ui';
import * as BuyerAccount from './BuyerAccount.ui';
import * as CommonText from './CommonText.ui';
import * as ExpressLogistics from './ExpressLogistics.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as OrderMain from './OrderMain.ui';
import * as ReturnDetail from './ReturnDetail.ui';
import * as ReturnMain from './ReturnMain.ui';
import * as DxOrderDetail from './DxOrderDetail.ui';
import * as DxReturnDetail from './DxReturnDetail.ui';
import * as IxCustomerReturnable from './IxCustomerReturnable.ui';

export function setUI(uq: Uq) {
	Object.assign(uq.Coupon, Coupon);
	Object.assign(uq.Chemical, Chemical);
	Object.assign(uq.SalesRegion, SalesRegion);
	Object.assign(uq.Currency, Currency);
	Object.assign(uq.PackType, PackType);
	Object.assign(uq.Address, Address);
	Object.assign(uq.Country, Country);
	Object.assign(uq.Province, Province);
	Object.assign(uq.City, City);
	Object.assign(uq.County, County);
	Object.assign(uq.InvoiceType, InvoiceType);
	Object.assign(uq.Customer, Customer);
	Object.assign(uq.Organization, Organization);
	Object.assign(uq.Contact, Contact);
	Object.assign(uq.InvoiceInfo, InvoiceInfo);
	Object.assign(uq.Brand, Brand);
	Object.assign(uq.ProductX, ProductX);
	Object.assign(uq.Warehouse, Warehouse);
	Object.assign(uq.WebUser, WebUser);
	Object.assign(uq.BuyerAccount, BuyerAccount);
	Object.assign(uq.CommonText, CommonText);
	Object.assign(uq.ExpressLogistics, ExpressLogistics);
	Object.assign(uq.OrderDetail, OrderDetail);
	Object.assign(uq.OrderMain, OrderMain);
	Object.assign(uq.ReturnDetail, ReturnDetail);
	Object.assign(uq.ReturnMain, ReturnMain);
	Object.assign(uq.DxOrderDetail, DxOrderDetail);
	Object.assign(uq.DxReturnDetail, DxReturnDetail);
	Object.assign(uq.IxCustomerReturnable, IxCustomerReturnable);
}
export * from './JkOrder';
